### ISSUE TITLE
GTFS parsing crashes

### ISSUE THREAD

**Issue by koenvanhollebeke** [Gabboxl/gtfs-osm-import#16]
Hi, 
Trying this out with this [GTFS](https://tursib.ro/documents/gtfs/tursib.gtfs_2023-06-v1.zip), with the **DefaultPlugin** selected in the configuration file (gtfs-import.properties), and launching `java -Xms512m -Xmx1g -jar gtfs-osm-import.jar stops` leads to:

> Loading config properties...
Config properties loaded successfully.

> Welcome to GTFS-OSM-Import!

> Downloading and extracting GTFS data from https://tursib.ro/documents/gtfs/tursib.gtfs_2023-06-v1.zip ...
java.lang.NullPointerException: Cannot invoke "it.osm.gtfs.enums.OSMStopType.equals(Object)" because "stopType" is null
	at it.osm.gtfs.input.GTFSParser.readStops(GTFSParser.java:106)
	at it.osm.gtfs.commands.CmdUpdateGTFSOSMData.updateBusStops(CmdUpdateGTFSOSMData.java:76)
	at it.osm.gtfs.commands.CmdUpdateGTFSOSMData.call(CmdUpdateGTFSOSMData.java:59)
	at it.osm.gtfs.commands.CmdGenerateBusStopsImport.call(CmdGenerateBusStopsImport.java:62)
	at it.osm.gtfs.commands.CmdGenerateBusStopsImport.call(CmdGenerateBusStopsImport.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at it.osm.gtfs.GTFSOSMImport.main(GTFSOSMImport.java:211)

A quick comparison of the gtfs data used (Turin) and the ones above shows no strings present in this case. Is a rebuild necessary after changing the configuration file (gtfs-import.properties)? Trying to select the **GTFSPlugin** in the configuration file leads to:

> Loading config properties...
Exception in thread "main" java.lang.IllegalArgumentException: An error occurred while loading config properties: The specified plugin was not found or is not valid
	at it.osm.gtfs.utils.GTFSImportSettings.<init>(GTFSImportSettings.java:101)
	at it.osm.gtfs.utils.GTFSImportSettings.init(GTFSImportSettings.java:106)
	at it.osm.gtfs.GTFSOSMImport.main(GTFSOSMImport.java:196)

OS = Ubuntu22.04
gtfs-osm-import.jar from the latest built

**Comment by Gabboxl** [comment]
Hi!

> Is a rebuild necessary after changing the configuration file (gtfs-import.properties)?

No, changing the `gtfs-import.properties` configuration file does not require a rebuild. If you created a new plugin class, then you need to recompile it, because that new class needs to be embedded into the .jar file.

> Trying to select the GTFSPlugin in the configuration file leads to:

I don't understand what do you mean with selecting `GTFSPlugin`, do you mean the interface? If so, you can't select the  `GTFSPlugin` interface class, you need to create a new class that *extends* the  `GTFSPlugin` interface. Then you implement the various methods the way you want.

Could you post your `gtfs-import.properties` file here, please?

**Comment by Gabboxl** [comment]
Okay, I tried using your GTFS data with the `DefaultPlugin`, and in fact it crashes for the same reason, which is that the `getStopType` method returns null (i need to change that for the default plugin). 

To resolve this you need to implement your plugin, if all the stops in your GTFS data are all bus stops, you can return a `OSMStopType.PHYSICAL_BUS_STOP` always, for example.

Let me know if you need help with that.

**Comment by koenvanhollebeke** [comment]
HI,

This is the gtfs-import.properties file which I used:

> #Url to the GTFS zip file
gtfs_zip_url=https://tursib.ro/documents/gtfs/tursib.gtfs_2023-06-v1.zip
#Path where this tool will generate its files
output_path=//home/koenvh/gtfs-osm-import/
#value of the operator tag for the bus stop nodes used to filter OSM stops
operator=Tursib
#Value of the OSM network tag - used to get relations' data from OSM
network=Tursib
#Whether to add a tag to every stop/route to identify imports that still weren't manually checked (default is true)
revised_key=true
#Plugin class path to use to preprocess the stops' data (if not specified, no preprocessing will be done)
#You can use the DefaultPlugin class plugin for a standard preprocess of stops' data even though is NOT recommended. Create a custom plugin instead.
plugin=it.osm.gtfs.plugins.DefaultPlugin
#The URL pointing to the Overpass API interpreter - Available public instances are documented here: https://wiki.openstreetmap.org/wiki/Overpass_API
overpass_api_server=https://maps.mail.ru/osm/tools/overpass/api/interpreter

> To resolve this you need to implement your plugin, if all the stops in your GTFS data are all bus stops, you can return a OSMStopType.PHYSICAL_BUS_STOP always, for example.
> 
> Let me know if you need help with that.

If you could indicate how this would be done for the fixBusStopName would be great - I am not really a good programmer...

`public class DefaultPlugin implements GTFSPlugin {
    @Override
    public String fixBusStopName(GTFSStop gtfsStop) {
        return gtfsStop.getName();
    }`

Maybe you could also give your thoughts about the following: I want to use your code for generating a list of osm xml files which indicate the public transport differences between the GTFS files (stops and routes) and what is available on OSM. Goal is to merge this data with the existing osm xml data of a region in order to use it offline in Osmand (converted by their osmandmapsgenerator). Problematic point might be the non existing osm ids of nodes/ways/routes of the differences between GTFS and OSM, but I tested that artificial osm id numbers do work in Osmand offline as long as the order (small to large ids) in the osm xml file is respected. 
I do want to have the recent public transport on android (offline) with me but and being able to update it easily whenever it changes. Most if not all apps (including google) don't work offline. Osmand/Mapsme seems to be the exception, with the limitation that you do not get timings of the public transport.

I also checked out [pfeadle](https://github.com/ad-freiburg/pfaedle) for the generation of mapmatched paths of the public transport routes but it doesn't return the differences in an easy way in osm xml format. It is great for the mapmatching of public transport routes though.
[Mapsme/organicmaps](https://github.com/organicmaps/organicmaps/tree/89ccee343eb1046f9c0d18963087350ae7a3cf13/tools/python/maps_generator) should have GTFS support in principle but it doesn't seem to work, and has the disadvantage that the maps format is binary and not easily accessible.

**Comment by Gabboxl** [comment]
Okay so, I fixed the `DefaultPlugin` behavior, now it returns a physical bus stop type as default. Try using the jar version 1.1.0 that I just released.

So, to get xml files of the differences between OSM and GTFS stops, you can use the `stops` command. 
While regarding the differences between OSM and GTFS routes fuctionality, it is not supported right now.

Let me know if the new version works.

**Comment by koenvanhollebeke** [comment]
Hi, yes it does. will take me some time to review the results. Thanks a lot
