### ISSUE TITLE
add additional roles on the members check in OSMParser.java

### ISSUE THREAD

**Issue by koenvanhollebeke** [Gabboxl/gtfs-osm-import#17]
Hi,
I think the relation member roles "platform_exit_only" and "platform_entry_only" for buses (but I have seen this also for ferries) and "stop_exit_only" and "stop_entry_only" should be added - [ref](https://wiki.openstreetmap.org/wiki/Buses), [PTv2](https://wiki.openstreetmap.org/w/index.php?oldid=1550843) - I get warning like:

> Warning: Relation 5474612 has a member node with an unsupported role "platform_entry_only", node ref/Id = 3729055350
Warning: Relation 5474612 has a member node with an unsupported role "platform_exit_only", node ref/Id = 8255207189
Warning: Relation 5474612 has a member node with an unsupported role "stop_exit_only", node ref/Id = 8255207188
Warning: Relation 5474612 has a member node with an unsupported role "stop_entry_only", node ref/Id = 3150475960
Warning: Relation 5474641 has a member node with an unsupported role "stop_exit_only", node ref/Id = 3729120340
Warning: Relation 5474641 has a member node with an unsupported role "platform_entry_only", node ref/Id = 3729119504
Warning: Relation 5474641 has a member node with an unsupported role "stop_entry_only", node ref/Id = 3729120336
Warning: Relation 5474641 has a member node with an unsupported role "platform_entry_only", node ref/Id = 3729119511
Warning: Relation 5474641 has a member node with an unsupported role "stop_entry_only", node ref/Id = 4322954831
Warning: Relation 5474641 has a member node with an unsupported role "platform_exit_only", node ref/Id = 3729119498

As far as I can see the check is in OSMParser.java on line 431:

> if (tempMemberRole.equals("stop") || tempMemberRole.equals("platform")) {
   OSMStop osmStop = stopsWithOSMIndex.get(tempMemberRef);

**Comment by Gabboxl** [comment]
Alright, will look into it this afternoon

**Comment by Gabboxl** [comment]
The version **1.2.0** adds these new roles. I'm closing the issue.
