### ISSUE TITLE
Error with UTF-8 characters in outputted `.osm` file for stops

### ISSUE THREAD

**Issue by wolfy1339** [Gabboxl/gtfs-osm-import#56]
In the outputted *.osm file for stops, there is an issue with encoding UTF-8 characters

Specifically, it's encoding a `é` as `Ã©`

**Comment by Gabboxl** [comment]
thanks, will fix it

**Comment by wolfy1339** [comment]
To add a bit more context, in the `gtfs-import.properties` file I entered the operator's name which contains the `é` character.


There is the stop name from the GTFS feed, and from the `gtfs-import.properties` file
