### ISSUE TITLE
Diacritics corruption in network name

### ISSUE THREAD

**Issue by ImenaOphelia** [Gabboxl/gtfs-osm-import#58]
Hello, thank you for your tool. However, when trying to convert data for some Polish cities I noticed it doesn't handle diacritcs correctly which results in stops mismatch. Example:
![image](https://github.com/user-attachments/assets/b3489ccf-0f2f-4b30-a20d-7bf730718de7)
The config file
![image](https://github.com/user-attachments/assets/1bf6595c-3d51-4f74-8322-5c5dba4c0050)
Output of `java -jar gtfs-osm-import.jar conf`
![image](https://github.com/user-attachments/assets/04e7dbe6-bb94-4c1f-81fa-399c042fc995)
Logs of `java -jar gtfs-osm-import.jar stops`
This doesn't happen with operator name. However, there's a little bug where if the operator name has multiple words then you have to wrap it in quotes for it to work.
Thank you in advance!

**Comment by Gabboxl** [comment]
Hi, thanks for the report. It should be fixed in the 1.3.0 release: https://github.com/Gabboxl/gtfs-osm-import/releases/latest

Make sure to save your `gtfs-import.properties` file with UTF-8 encoding.
